FROM nginx:1.15.6

COPY nginx.sh /etc/init.d/nginx.sh
RUN chmod +x /etc/init.d/nginx.sh

COPY start.sh /root

COPY default.conf /etc/nginx/conf.d/default.conf
RUN sed -i 's/{{php-fpm-server_name}}/php5.6-fpm/' /etc/nginx/conf.d/default.conf

ENTRYPOINT ["/bin/bash", "/root/start.sh"]